Add more resources
Jim-Hodapp-Coaching/refactor-platform-rs pull request #62
Opened 2024-08-14 13:54 UTC by calebbourg

## Description
_describe the intent of your changes here_

#### GitHub Issue: [Closes|Fixes|Resolves] #_your GitHub issue number here_

### Changes
* ...
* ...
* ...

### Testing Strategy
_describe how you or someone else can test and verify the changes_

### Concerns
_describe any concerns that might be worth mentioning or discussing_

2024-08-21 12:51 UTC, calebbourg commented
Here is the new PNG of the dbml diagram. I can never remember how to add it through the GitHub UI.

![Untitled (1)](https://github.com/user-attachments/assets/c757c7fd-98e7-4075-943b-1fbdf5157053)

2024-08-21 14:38 UTC, jhodapp commented
> Here is the new PNG of the dbml diagram. I can never remember how to add it through the GitHub UI.

I'll document that here: the PNG goes into src/entity/README.md. You can edit that file from GitHub itself within your PR here and drag and drop the updated PNG onto that file at the correct line within the file. GitHub uploads the updated diagram and creates a new markdown link to the file via a URI and UUID right where your cursor is.

2024-08-21 14:49 UTC, jhodapp requested changes
Just some very minor string constant updates to fix and then I'll approve this PR. This is an exciting milestone of a PR!

2024-08-21 14:49 UTC, jhodapp commented on web/src/controller/agreement_controller.rs
> +        (status = 404, description = "Note not found"),
```suggestion
        (status = 404, description = "Agreement not found"),
```

2024-08-21 14:49 UTC, jhodapp commented on web/src/controller/action_controller.rs
> +        (status = 404, description = "Note not found"),
```suggestion
        (status = 404, description = "Action not found"),
```

2024-08-21 14:49 UTC, jhodapp commented on web/src/controller/overarching_goal_controller.rs
> +        (status = 404, description = "Note not found"),
```suggestion
        (status = 404, description = "Overarching Goal not found"),
```

2024-08-21 14:49 UTC, jhodapp commented on web/src/controller/overarching_goal_controller.rs
> +        (status = 201, description = "Successfully Created a New OverarchingGoal", body = [entity::overarching_goals::Model]),
```suggestion
        (status = 201, description = "Successfully Created a New Overarching Goal", body = [entity::overarching_goals::Model]),
```

2024-08-21 14:49 UTC, jhodapp commented on web/src/controller/overarching_goal_controller.rs
> +    debug!("GET all OverarchingGoals");
```suggestion
    debug!("GET all Overarching Goals");
```

2024-08-23 18:00 UTC, jhodapp approved these changes
Looks fabulous!

2024-08-23 18:00 UTC, merged